// create/templates/react/pages/catalog.jsx
import React from 'react';
import { Page, Navbar, List, ListItem } from 'framework7-cn-react';

export default class extends React.Component {
  constructor() {
    super();

    this.state = {
      products: this.$f7.data.products,
    }
  }
  render() {
    return (
      <Page name="catalog">
        <Navbar title="Catalog" />
        <List>
          {this.state.products.map((product) => (
            <ListItem
              key={product.id}
              title={product.title}
              link={`/product/${product.id}/`}
            />
          ))}
        </List>
      </Page>
    );
  }
}

// create/templates/svelte/pages/catalog.svelte
<Page name="catalog">
  <Navbar title="Catalog" />
  <List>
    {#each products as product, index (product.id)}
      <ListItem
        title={product.title}
        link={`/product/${product.id}/`}
      />
    {/each}
  </List>
</Page>
<script>
  import { f7ready, f7, Page, Navbar, List, ListItem } from 'framework7-cn-svelte';

  let products = [];

  f7ready(() => {
    products = f7.data.products;
  });
</script>
