// create/templates/react/pages/product.jsx
import React from 'react';
import { Page, Navbar, BlockTitle, Block } from 'framework7-cn-react';

export default class extends React.Component {
  constructor(props) {
    super(props);
    var productId = props.f7route.params.id;
    var currentProduct;
    this.$f7.data.products.forEach(function (product) {
      if (product.id === productId) {
        currentProduct = product;
      }
    });

    this.state = {
      product: currentProduct,
    };

  }
  render() {
    return (
      <Page name="product">
        <Navbar title={this.state.product.title} backLink="Back" />
        <BlockTitle>About {this.state.product.title}</BlockTitle>
        <Block strong>
          {this.state.product.description}
        </Block>
      </Page>
    );
  }
}

// create/templates/svelte/pages/product.svelte
<Page name="product">
  <Navbar title={currentProduct.title} backLink="Back" />
  <BlockTitle>About {currentProduct.title}</BlockTitle>
  <Block strong>
    {currentProduct.description}
  </Block>
</Page>
<script>
  import { f7, Page, Navbar, BlockTitle, Block } from 'framework7-cn-svelte';

  export let f7route;

  const productId = f7route.params.id;
  let currentProduct;
  f7.data.products.forEach(function (product) {
    if (product.id === productId) {
      currentProduct = product;
    }
  });
</script>
